name: 'logging'
version: '1.0'

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"


on-run-start:
  - "{%- if var('run_dbt_logging', false) -%} {{ logging.create_audit_schema( var('run_dbt_logging', false)) }} {%- endif -%}"
  - "{%- if var('run_dbt_logging', false) -%} {{ logging.create_audit_log_table( var('run_dbt_logging', false)) }} {%- endif -%}"
  - "{%- if var('run_dbt_logging', false) -%} {{ logging.log_run_start_event( var('run_dbt_logging', false)) }} {%- endif -%}"


on-run-end:
  - "{%- if var('run_dbt_logging', false) -%} {{ logging.log_run_end_event( var('run_dbt_logging', false)) }} {%- endif -%}"
  - "{%- if var('run_dbt_logging', false) -%} {{ logging.unload_to_s3( var('unload_to_s3', false) )}} {%- endif -%}"


models:
  logging:
    schema: meta
