name: 'logging'
version: '0.5.0'
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

vars:
    event_log_target_name: prod

on-run-start:
  - "{{ logging.create_audit_schema() }}"
  - "{{ logging.create_audit_log_table() }}"
  - "{{ logging.log_run_start_event() }}"


on-run-end:
  - "{{ logging.log_run_end_event() }}"


models:
  logging:
    +schema: meta
    bigquery:
      +enabled: '{{ target.type == "bigquery" | as_bool }}'
    spark:
      +enabled: '{{ target.type == "spark" | as_bool }}'
    default:
      +enabled: '{{ target.type != "bigquery" and target.type == "spark" | as_bool }}'
