name: 'logging'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

on-run-start:
  - "{{ logging.logging_target_create_audit_schema() }}"
  - "{{ logging.logging_target_create_audit_log_table() }}"
  - "{{ logging.logging_target_start() }}"

on-run-end:
  - "{{ logging.logging_target_end() }}"

models:
  logging:
    schema: logging
