
name: 'event_logging_integration_tests'
version: '0.3.0'
config-version: 2

profile: 'integration_tests'


models:
  pre-hook: "{{ logging.log_model_start_event() }}"
  post-hook: "{{ logging.log_model_end_event() }}"
